services:
  mysql:
    image: mysql:8.0
    container_name: smartphone_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smartphone_intelligence
      MYSQL_USER: app_user
      MYSQL_PASSWORD: Study@123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
